name: Octopus
version: 1.0.0
main: octova.Octopus
api-version: 1.19

commands:
  snake:
    description: Join to the snake game
    usage: /snake
    
  snakeboard:
    description: Join to the snake game
    usage: /snakeboard <size> <x> <y> <z>

  speed:
    description: Join to the incremental speed game
    usage: /speed